// IPIP-NEO 120 (Johnson, 2014). Butir domain publik dari ipip.ori.org.
// d = domain, f = facet, r = 1 berarti nilainya dibalik.
window.BUTIR = [
  {"t":"Saya gampang khawatir.","d":"N","f":1,"r":0},
  {"t":"Saya gampang akrab dengan orang baru.","d":"E","f":1,"r":0},
  {"t":"Imajinasi saya kuat.","d":"O","f":1,"r":0},
  {"t":"Saya percaya pada orang lain.","d":"A","f":1,"r":0},
  {"t":"Saya menyelesaikan tugas dengan baik.","d":"C","f":1,"r":0},
  {"t":"Saya gampang marah.","d":"N","f":2,"r":0},
  {"t":"Saya suka acara besar yang ramai.","d":"E","f":2,"r":0},
  {"t":"Menurut saya seni itu penting.","d":"O","f":2,"r":0},
  {"t":"Saya memanfaatkan orang lain demi kepentingan sendiri.","d":"A","f":2,"r":1},
  {"t":"Saya suka beres-beres.","d":"C","f":2,"r":0},
  {"t":"Saya sering merasa sedih.","d":"N","f":3,"r":0},
  {"t":"Saya biasa maju memimpin.","d":"E","f":3,"r":0},
  {"t":"Saya merasakan emosi dengan sangat kuat.","d":"O","f":3,"r":0},
  {"t":"Saya senang membantu orang lain.","d":"A","f":3,"r":0},
  {"t":"Saya menepati janji.","d":"C","f":3,"r":0},
  {"t":"Saya merasa sulit mendekati orang lain.","d":"N","f":4,"r":0},
  {"t":"Saya selalu sibuk.","d":"E","f":4,"r":0},
  {"t":"Saya lebih suka variasi daripada rutinitas.","d":"O","f":4,"r":0},
  {"t":"Saya suka adu mulut yang seru.","d":"A","f":4,"r":1},
  {"t":"Saya bekerja keras.","d":"C","f":4,"r":0},
  {"t":"Saya suka kalap: makan, belanja, atau main sampai kebablasan.","d":"N","f":5,"r":0},
  {"t":"Saya suka hal-hal yang memacu adrenalin.","d":"E","f":5,"r":0},
  {"t":"Saya suka bacaan yang menantang pikiran.","d":"O","f":5,"r":0},
  {"t":"Saya merasa lebih baik daripada orang lain.","d":"A","f":5,"r":1},
  {"t":"Saya selalu punya persiapan.","d":"C","f":5,"r":0},
  {"t":"Saya gampang panik.","d":"N","f":6,"r":0},
  {"t":"Saya membawa suasana ceria.","d":"E","f":6,"r":0},
  {"t":"Saya cenderung memilih calon pemimpin yang membawa pembaruan.","d":"O","f":6,"r":0},
  {"t":"Saya kasihan melihat orang yang hidup di jalanan.","d":"A","f":6,"r":0},
  {"t":"Saya langsung terjun tanpa pikir panjang.","d":"C","f":6,"r":1},
  {"t":"Saya takut hal terburuk akan terjadi.","d":"N","f":1,"r":0},
  {"t":"Saya nyaman berada di tengah orang-orang.","d":"E","f":1,"r":0},
  {"t":"Saya menikmati khayalan yang liar.","d":"O","f":1,"r":0},
  {"t":"Saya percaya orang lain berniat baik.","d":"A","f":1,"r":0},
  {"t":"Saya jago dalam hal yang saya kerjakan.","d":"C","f":1,"r":0},
  {"t":"Saya gampang kesal.","d":"N","f":2,"r":0},
  {"t":"Di acara ramai, saya mengobrol dengan banyak orang.","d":"E","f":2,"r":0},
  {"t":"Saya melihat keindahan pada hal yang luput dari perhatian orang lain.","d":"O","f":2,"r":0},
  {"t":"Saya rela curang supaya bisa unggul.","d":"A","f":2,"r":1},
  {"t":"Saya sering lupa mengembalikan barang ke tempatnya.","d":"C","f":2,"r":1},
  {"t":"Saya tidak suka dengan diri sendiri.","d":"N","f":3,"r":0},
  {"t":"Saya berusaha memimpin orang lain.","d":"E","f":3,"r":0},
  {"t":"Saya ikut merasakan emosi orang lain.","d":"O","f":3,"r":0},
  {"t":"Saya peduli pada orang lain.","d":"A","f":3,"r":0},
  {"t":"Saya berkata jujur.","d":"C","f":3,"r":0},
  {"t":"Saya takut jadi pusat perhatian.","d":"N","f":4,"r":0},
  {"t":"Saya selalu bergerak, jarang diam.","d":"E","f":4,"r":0},
  {"t":"Saya lebih suka bertahan dengan hal yang sudah saya kenal.","d":"O","f":4,"r":1},
  {"t":"Saya membentak orang.","d":"A","f":4,"r":1},
  {"t":"Saya mengerjakan lebih dari yang diharapkan.","d":"C","f":4,"r":0},
  {"t":"Saya jarang kebablasan menuruti keinginan.","d":"N","f":5,"r":1},
  {"t":"Saya suka mencari petualangan.","d":"E","f":5,"r":0},
  {"t":"Saya menghindari obrolan yang terlalu filosofis.","d":"O","f":5,"r":1},
  {"t":"Saya bangga sekali pada diri sendiri.","d":"A","f":5,"r":1},
  {"t":"Saya menjalankan rencana yang sudah saya buat.","d":"C","f":5,"r":0},
  {"t":"Saya gampang kewalahan menghadapi keadaan.","d":"N","f":6,"r":0},
  {"t":"Saya sering bersenang-senang.","d":"E","f":6,"r":0},
  {"t":"Saya percaya tidak ada benar dan salah yang mutlak.","d":"O","f":6,"r":0},
  {"t":"Saya iba pada orang yang nasibnya kurang beruntung.","d":"A","f":6,"r":0},
  {"t":"Saya mengambil keputusan dengan gegabah.","d":"C","f":6,"r":1},
  {"t":"Saya takut pada banyak hal.","d":"N","f":1,"r":0},
  {"t":"Saya menghindari berurusan dengan orang lain.","d":"E","f":1,"r":1},
  {"t":"Saya suka melamun.","d":"O","f":1,"r":0},
  {"t":"Saya percaya pada ucapan orang.","d":"A","f":1,"r":0},
  {"t":"Saya menangani tugas dengan lancar.","d":"C","f":1,"r":0},
  {"t":"Emosi saya gampang meledak.","d":"N","f":2,"r":0},
  {"t":"Saya lebih suka sendirian.","d":"E","f":2,"r":1},
  {"t":"Saya tidak suka puisi.","d":"O","f":2,"r":1},
  {"t":"Saya mengambil keuntungan dari orang lain.","d":"A","f":2,"r":1},
  {"t":"Saya membiarkan kamar berantakan.","d":"C","f":2,"r":1},
  {"t":"Saya sering merasa terpuruk.","d":"N","f":3,"r":0},
  {"t":"Saya suka mengatur jalannya suatu urusan.","d":"E","f":3,"r":0},
  {"t":"Saya jarang menyadari reaksi emosi saya sendiri.","d":"O","f":3,"r":1},
  {"t":"Saya tidak ambil pusing dengan perasaan orang lain.","d":"A","f":3,"r":1},
  {"t":"Saya melanggar aturan.","d":"C","f":3,"r":1},
  {"t":"Saya hanya nyaman kalau bersama teman dekat.","d":"N","f":4,"r":0},
  {"t":"Saya mengisi waktu luang dengan banyak kegiatan.","d":"E","f":4,"r":0},
  {"t":"Saya tidak suka perubahan.","d":"O","f":4,"r":1},
  {"t":"Saya menghina orang.","d":"A","f":4,"r":1},
  {"t":"Saya bekerja secukupnya, asal beres.","d":"C","f":4,"r":1},
  {"t":"Saya gampang menahan godaan.","d":"N","f":5,"r":1},
  {"t":"Saya senang bertindak nekat.","d":"E","f":5,"r":0},
  {"t":"Saya sulit memahami ide yang abstrak.","d":"O","f":5,"r":1},
  {"t":"Saya menganggap diri saya hebat.","d":"A","f":5,"r":1},
  {"t":"Saya membuang-buang waktu.","d":"C","f":5,"r":1},
  {"t":"Saya merasa tidak sanggup menghadapi masalah.","d":"N","f":6,"r":0},
  {"t":"Saya sangat menikmati hidup.","d":"E","f":6,"r":0},
  {"t":"Saya cenderung memilih calon pemimpin yang menjaga tradisi.","d":"O","f":6,"r":1},
  {"t":"Saya tidak tertarik dengan masalah orang lain.","d":"A","f":6,"r":1},
  {"t":"Saya terburu-buru dalam bertindak.","d":"C","f":6,"r":1},
  {"t":"Saya gampang stres.","d":"N","f":1,"r":0},
  {"t":"Saya menjaga jarak dari orang lain.","d":"E","f":1,"r":1},
  {"t":"Saya suka tenggelam dalam pikiran sendiri.","d":"O","f":1,"r":0},
  {"t":"Saya sulit percaya pada orang.","d":"A","f":1,"r":1},
  {"t":"Saya tahu cara menuntaskan pekerjaan.","d":"C","f":1,"r":0},
  {"t":"Saya tidak gampang jengkel.","d":"N","f":2,"r":1},
  {"t":"Saya menghindari keramaian.","d":"E","f":2,"r":1},
  {"t":"Saya tidak menikmati kunjungan ke museum atau pameran seni.","d":"O","f":2,"r":1},
  {"t":"Saya menghalangi rencana orang lain.","d":"A","f":2,"r":1},
  {"t":"Saya menaruh barang sembarangan.","d":"C","f":2,"r":1},
  {"t":"Saya nyaman dengan diri sendiri.","d":"N","f":3,"r":1},
  {"t":"Saya menunggu orang lain yang memimpin.","d":"E","f":3,"r":1},
  {"t":"Saya tidak paham dengan orang yang gampang terbawa perasaan.","d":"O","f":3,"r":1},
  {"t":"Saya tidak meluangkan waktu untuk orang lain.","d":"A","f":3,"r":1},
  {"t":"Saya mengingkari janji.","d":"C","f":3,"r":1},
  {"t":"Saya santai saja di situasi yang canggung.","d":"N","f":4,"r":1},
  {"t":"Saya suka santai-santai saja.","d":"E","f":4,"r":1},
  {"t":"Saya berpegang pada cara lama yang sudah umum.","d":"O","f":4,"r":1},
  {"t":"Saya membalas perlakuan buruk orang lain.","d":"A","f":4,"r":1},
  {"t":"Saya tidak banyak mencurahkan waktu dan tenaga untuk pekerjaan.","d":"C","f":4,"r":1},
  {"t":"Saya bisa mengendalikan keinginan saya.","d":"N","f":5,"r":1},
  {"t":"Saya suka bertingkah gila-gilaan.","d":"E","f":5,"r":0},
  {"t":"Saya tidak tertarik membahas teori.","d":"O","f":5,"r":1},
  {"t":"Saya membanggakan kelebihan diri sendiri.","d":"A","f":5,"r":1},
  {"t":"Saya sulit memulai tugas.","d":"C","f":5,"r":1},
  {"t":"Saya tetap tenang di bawah tekanan.","d":"N","f":6,"r":1},
  {"t":"Saya selalu melihat sisi baik dari keadaan.","d":"E","f":6,"r":0},
  {"t":"Saya percaya pelaku kejahatan harus dihukum keras.","d":"O","f":6,"r":1},
  {"t":"Saya memilih tidak memikirkan orang yang hidupnya susah.","d":"A","f":6,"r":1},
  {"t":"Saya bertindak tanpa berpikir.","d":"C","f":6,"r":1}
]
